name: Deployment Project
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: This step is used to get code using pre-defined github actions 
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
  secondJob:
    runs-on: ubuntu-latest
    steps:
      - name: Testing prallell jobs
        run: echo "This is a test" 